# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: CF CLI Action
        # You may pin to the exact commit or the version.
        # uses: citizen-of-planet-earth/cf-cli-action@0973ff9ead09c08129810ccdea90d7bc32efde00
        uses: citizen-of-planet-earth/cf-cli-action@v1
        with:
          # Target API Endpoint of Cloud Foundry
          cf_api: https://api.cf.eu10.hana.ondemand.com
          # Username for API authentication
          cf_username: test@test.com
          # Password for API authentication
          cf_password: test
          # Target Organization
          cf_org: 2
          # Target Space
          # Command to run using CF CLI
          command: cf push
     
